name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_ORG_ID: team_hAybTDwdviVFT7lS3Rc2ljrm
          VERCEL_PROJECT_ID: prj_0P97yiJK2gYAEnF2tCfkMTwRmiDD
